-- Create the page_views table to track visitors
CREATE TABLE IF NOT EXISTS public.page_views (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  slug TEXT NOT NULL,
  view_count BIGINT DEFAULT 1 NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Create a unique index on the slug column to ensure uniqueness
CREATE UNIQUE INDEX IF NOT EXISTS page_views_slug_idx ON public.page_views (slug);

-- Enable row-level security
ALTER TABLE public.page_views ENABLE ROW LEVEL SECURITY;

-- Create a policy to allow all authenticated users to select from the table
CREATE POLICY "Allow all users to read page_views" 
  ON public.page_views FOR SELECT 
  USING (true);

-- Enable realtime for page_views table - add to publication
BEGIN;
  -- Create the publication if it doesn't exist
  SELECT pg_catalog.pg_publication_tables('supabase_realtime', 'public', 'page_views');
EXCEPTION WHEN undefined_object THEN
  CREATE PUBLICATION supabase_realtime;
END;

-- Add the page_views table to the realtime publication
ALTER PUBLICATION supabase_realtime ADD TABLE public.page_views;

-- Create a function to increment the page view count
CREATE OR REPLACE FUNCTION public.increment_page_view(page_slug TEXT)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
    IF EXISTS (SELECT FROM public.page_views WHERE slug = page_slug) THEN
        UPDATE public.page_views
        SET view_count = view_count + 1,
            updated_at = timezone('utc'::text, now())
        WHERE slug = page_slug;
    ELSE
        INSERT INTO public.page_views(slug, view_count, created_at, updated_at) 
        VALUES (page_slug, 1, timezone('utc'::text, now()), timezone('utc'::text, now()));
    END IF;
END;
$$;

-- Create a function to get a page's view count
CREATE OR REPLACE FUNCTION public.get_page_view_count(page_slug TEXT)
RETURNS TABLE (view_count BIGINT)
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
    RETURN QUERY
    SELECT pv.view_count
    FROM public.page_views pv
    WHERE pv.slug = page_slug;
END;
$$; 