import {
  Settings,
  Mail,
  Bell,
  Shield,
  Palette,
  Globe,
  Zap,
  Database,
} from "lucide-react";
import { validateEmail, validateURL } from "./validation";
import type { SettingDefinition, SettingCategory } from "../types/settings";

export const settingDefinitions: Record<string, SettingDefinition> = {
  // General Settings
  "app.name": {
    key: "app.name",
    label: "Application Name",
    description: "Name displayed throughout the admin panel",
    category: "general",
    group: "Application",
    type: "text",
    defaultValue: "Cenety Admin",
    placeholder: "Enter application name",
  },
  "app.url": {
    key: "app.url",
    label: "Application URL",
    description: "Base URL of the application",
    category: "general",
    group: "Application",
    type: "url",
    defaultValue: "https://admin.cenety.com",
    validation: validateURL,
    placeholder: "https://admin.example.com",
  },
  "app.timezone": {
    key: "app.timezone",
    label: "Default Timezone",
    description: "Default timezone for the application",
    category: "general",
    group: "Application",
    type: "select",
    defaultValue: "UTC",
    options: [
      "UTC",
      "Europe/Berlin",
      "Europe/London",
      "America/New_York",
      "America/Los_Angeles",
      "Asia/Tokyo",
      "Asia/Shanghai",
    ],
  },
  "app.maintenance_mode": {
    key: "app.maintenance_mode",
    label: "Maintenance Mode",
    description: "Enable maintenance mode (users will see maintenance page)",
    category: "general",
    group: "Application",
    type: "boolean",
    defaultValue: "false",
    helpText: "When enabled, all users except admins will see a maintenance page",
  },
  "app.support_email": {
    key: "app.support_email",
    label: "Support Email",
    description: "Email address for user support inquiries",
    category: "general",
    group: "Application",
    type: "email",
    defaultValue: "support@cenety.com",
    validation: validateEmail,
    placeholder: "support@example.com",
  },

  // Email Settings
  "email.provider": {
    key: "email.provider",
    label: "Email Provider",
    description: "Email service provider",
    category: "email",
    group: "SMTP Configuration",
    type: "select",
    defaultValue: "resend",
    options: ["resend", "smtp", "sendgrid", "mailgun"],
  },
  "email.from_address": {
    key: "email.from_address",
    label: "From Email Address",
    description: "Default sender email address",
    category: "email",
    group: "SMTP Configuration",
    type: "email",
    defaultValue: "noreply@cenety.com",
    validation: validateEmail,
    placeholder: "noreply@example.com",
  },
  "email.from_name": {
    key: "email.from_name",
    label: "From Name",
    description: "Default sender name",
    category: "email",
    group: "SMTP Configuration",
    type: "text",
    defaultValue: "Cenety",
    placeholder: "Your Company Name",
  },
  "email.smtp_host": {
    key: "email.smtp_host",
    label: "SMTP Host",
    description: "SMTP server hostname",
    category: "email",
    group: "SMTP Configuration",
    type: "text",
    defaultValue: "",
    placeholder: "smtp.example.com",
  },
  "email.smtp_port": {
    key: "email.smtp_port",
    label: "SMTP Port",
    description: "SMTP server port (usually 587 for TLS, 465 for SSL)",
    category: "email",
    group: "SMTP Configuration",
    type: "number",
    defaultValue: "587",
    placeholder: "587",
  },
  "email.smtp_user": {
    key: "email.smtp_user",
    label: "SMTP Username",
    description: "SMTP authentication username",
    category: "email",
    group: "SMTP Configuration",
    type: "text",
    defaultValue: "",
    placeholder: "your-email@example.com",
  },
  "email.smtp_password": {
    key: "email.smtp_password",
    label: "SMTP Password",
    description: "SMTP authentication password",
    category: "email",
    group: "SMTP Configuration",
    type: "password",
    defaultValue: "",
    sensitive: true,
    placeholder: "Enter SMTP password",
  },
  "email.smtp_encryption": {
    key: "email.smtp_encryption",
    label: "SMTP Encryption",
    description: "Encryption method for SMTP connection",
    category: "email",
    group: "SMTP Configuration",
    type: "select",
    defaultValue: "tls",
    options: ["none", "tls", "ssl"],
  },
  "email.resend_api_key": {
    key: "email.resend_api_key",
    label: "Resend API Key",
    description: "API key for Resend email service",
    category: "email",
    group: "Resend Configuration",
    type: "password",
    defaultValue: "",
    sensitive: true,
    placeholder: "re_xxxxxxxxxxxxx",
    helpText: "Get your API key from resend.com/api-keys",
  },

  // Notifications
  "notifications.enabled": {
    key: "notifications.enabled",
    label: "Enable Notifications",
    description: "Enable system-wide notifications",
    category: "notifications",
    group: "General",
    type: "boolean",
    defaultValue: "true",
  },
  "notifications.email_enabled": {
    key: "notifications.email_enabled",
    label: "Email Notifications",
    description: "Enable email notifications",
    category: "notifications",
    group: "Channels",
    type: "boolean",
    defaultValue: "true",
  },
  "notifications.push_enabled": {
    key: "notifications.push_enabled",
    label: "Push Notifications",
    description: "Enable browser push notifications",
    category: "notifications",
    group: "Channels",
    type: "boolean",
    defaultValue: "false",
  },
  "notifications.in_app_enabled": {
    key: "notifications.in_app_enabled",
    label: "In-App Notifications",
    description: "Enable in-app notification center",
    category: "notifications",
    group: "Channels",
    type: "boolean",
    defaultValue: "true",
  },

  // Security
  "security.require_2fa": {
    key: "security.require_2fa",
    label: "Require 2FA for Admins",
    description: "Require two-factor authentication for admin users",
    category: "security",
    group: "Authentication",
    type: "boolean",
    defaultValue: "false",
    helpText: "All admin users will be required to set up 2FA on next login",
  },
  "security.session_timeout": {
    key: "security.session_timeout",
    label: "Session Timeout (seconds)",
    description: "Automatic session timeout in seconds",
    category: "security",
    group: "Authentication",
    type: "number",
    defaultValue: "3600",
    placeholder: "3600",
    helpText: "Default: 3600 seconds (1 hour)",
  },
  "security.password_min_length": {
    key: "security.password_min_length",
    label: "Minimum Password Length",
    description: "Minimum required password length",
    category: "security",
    group: "Password Policy",
    type: "number",
    defaultValue: "8",
    placeholder: "8",
  },
  "security.password_require_uppercase": {
    key: "security.password_require_uppercase",
    label: "Require Uppercase",
    description: "Passwords must contain uppercase letters",
    category: "security",
    group: "Password Policy",
    type: "boolean",
    defaultValue: "true",
  },
  "security.password_require_numbers": {
    key: "security.password_require_numbers",
    label: "Require Numbers",
    description: "Passwords must contain numbers",
    category: "security",
    group: "Password Policy",
    type: "boolean",
    defaultValue: "true",
  },
  "security.password_require_symbols": {
    key: "security.password_require_symbols",
    label: "Require Symbols",
    description: "Passwords must contain special characters",
    category: "security",
    group: "Password Policy",
    type: "boolean",
    defaultValue: "false",
  },
  "security.rate_limit_enabled": {
    key: "security.rate_limit_enabled",
    label: "Enable Rate Limiting",
    description: "Enable rate limiting for API endpoints",
    category: "security",
    group: "API Security",
    type: "boolean",
    defaultValue: "true",
  },
  "security.rate_limit_requests": {
    key: "security.rate_limit_requests",
    label: "Rate Limit (requests per minute)",
    description: "Maximum requests per minute per IP",
    category: "security",
    group: "API Security",
    type: "number",
    defaultValue: "100",
    placeholder: "100",
  },

  // Appearance
  "appearance.theme": {
    key: "appearance.theme",
    label: "Theme",
    description: "Choose your preferred theme. Changes apply immediately.",
    category: "appearance",
    group: "Theme",
    type: "select",
    defaultValue: "system",
    options: ["light", "dark", "system"],
  },
  "appearance.primary_color": {
    key: "appearance.primary_color",
    label: "Primary Brand Color",
    description: "Primary brand color (hex code)",
    category: "appearance",
    group: "Branding",
    type: "text",
    defaultValue: "#000000",
    placeholder: "#000000",
    helpText: "Enter hex color code (e.g., #000000)",
  },
  "appearance.secondary_color": {
    key: "appearance.secondary_color",
    label: "Secondary Brand Color",
    description: "Secondary brand color (hex code)",
    category: "appearance",
    group: "Branding",
    type: "text",
    defaultValue: "#666666",
    placeholder: "#666666",
  },

  // Localization
  "localization.default_locale": {
    key: "localization.default_locale",
    label: "Default Locale",
    description: "Default language and region",
    category: "localization",
    group: "Language",
    type: "select",
    defaultValue: "en-US",
    options: ["en-US", "de-DE", "fr-FR", "es-ES", "it-IT", "pt-BR"],
  },
  "localization.default_currency": {
    key: "localization.default_currency",
    label: "Default Currency",
    description: "Default currency code",
    category: "localization",
    group: "Currency",
    type: "select",
    defaultValue: "EUR",
    options: ["EUR", "USD", "GBP", "JPY", "CHF", "CAD", "AUD"],
  },
  "localization.date_format": {
    key: "localization.date_format",
    label: "Date Format",
    description: "Default date display format",
    category: "localization",
    group: "Formats",
    type: "select",
    defaultValue: "DD.MM.YYYY",
    options: ["DD.MM.YYYY", "MM/DD/YYYY", "YYYY-MM-DD", "DD/MM/YYYY"],
  },
  "localization.time_format": {
    key: "localization.time_format",
    label: "Time Format",
    description: "Default time display format",
    category: "localization",
    group: "Formats",
    type: "select",
    defaultValue: "24h",
    options: ["12h", "24h"],
  },
  "localization.number_format": {
    key: "localization.number_format",
    label: "Number Format",
    description: "Default number format style",
    category: "localization",
    group: "Formats",
    type: "select",
    defaultValue: "european",
    options: ["european", "american"],
    helpText: "European: 1.234,56 | American: 1,234.56",
  },

  // Integrations
  "integrations.stripe_enabled": {
    key: "integrations.stripe_enabled",
    label: "Enable Stripe",
    description: "Enable Stripe payment integration",
    category: "integrations",
    group: "Payment Providers",
    type: "boolean",
    defaultValue: "false",
  },
  "integrations.stripe_api_key": {
    key: "integrations.stripe_api_key",
    label: "Stripe API Key",
    description: "Stripe secret API key",
    category: "integrations",
    group: "Payment Providers",
    type: "password",
    defaultValue: "",
    sensitive: true,
    placeholder: "sk_live_xxxxxxxxxxxxx",
  },
  "integrations.stripe_webhook_secret": {
    key: "integrations.stripe_webhook_secret",
    label: "Stripe Webhook Secret",
    description: "Stripe webhook signing secret",
    category: "integrations",
    group: "Payment Providers",
    type: "password",
    defaultValue: "",
    sensitive: true,
    placeholder: "whsec_xxxxxxxxxxxxx",
  },
  "integrations.polar_enabled": {
    key: "integrations.polar_enabled",
    label: "Enable Polar.sh",
    description: "Enable Polar.sh payment integration",
    category: "integrations",
    group: "Payment Providers",
    type: "boolean",
    defaultValue: "false",
  },
  "integrations.polar_api_key": {
    key: "integrations.polar_api_key",
    label: "Polar.sh API Key",
    description: "Polar.sh access token",
    category: "integrations",
    group: "Payment Providers",
    type: "password",
    defaultValue: "",
    sensitive: true,
    placeholder: "polar_xxxxxxxxxxxxx",
  },

  // Advanced
  "advanced.debug_mode": {
    key: "advanced.debug_mode",
    label: "Debug Mode",
    description: "Enable detailed error messages and logging",
    category: "advanced",
    group: "Development",
    type: "boolean",
    defaultValue: "false",
    helpText: "Only enable in development environments",
  },
  "advanced.log_level": {
    key: "advanced.log_level",
    label: "Log Level",
    description: "Minimum log level to record",
    category: "advanced",
    group: "Development",
    type: "select",
    defaultValue: "info",
    options: ["debug", "info", "warn", "error"],
  },
  "advanced.api_rate_limit": {
    key: "advanced.api_rate_limit",
    label: "API Rate Limit",
    description: "API requests per minute per IP",
    category: "advanced",
    group: "Performance",
    type: "number",
    defaultValue: "100",
    placeholder: "100",
  },
  "advanced.cache_ttl": {
    key: "advanced.cache_ttl",
    label: "Cache TTL (seconds)",
    description: "Default cache time-to-live in seconds",
    category: "advanced",
    group: "Performance",
    type: "number",
    defaultValue: "300",
    placeholder: "300",
    helpText: "Default: 300 seconds (5 minutes)",
  },
};

export const settingCategories: SettingCategory[] = [
  {
    id: "general",
    label: "General",
    icon: Settings,
    description: "Basic system settings and configuration",
  },
  {
    id: "email",
    label: "Email",
    icon: Mail,
    description: "Email server and notification settings",
  },
  {
    id: "notifications",
    label: "Notifications",
    icon: Bell,
    description: "Notification preferences and channels",
  },
  {
    id: "security",
    label: "Security",
    icon: Shield,
    description: "Security and authentication settings",
  },
  {
    id: "appearance",
    label: "Appearance",
    icon: Palette,
    description: "Theme and UI customization",
  },
  {
    id: "localization",
    label: "Localization",
    icon: Globe,
    description: "Language, currency, and regional settings",
  },
  {
    id: "integrations",
    label: "Integrations",
    icon: Zap,
    description: "Third-party service integrations",
  },
  {
    id: "advanced",
    label: "Advanced",
    icon: Database,
    description: "Advanced system configuration",
  },
];
